export const MOODS = [
  { id: "happy", name: "Happy", icon: "😊", color: "from-yellow-400 to-orange-400", translations: { en: "Happy", hi: "खुश", te: "సంతోషం" } },
  { id: "sad", name: "Sad", icon: "😢", color: "from-blue-400 to-indigo-400", translations: { en: "Sad", hi: "उदास", te: "విచారంగా" } },
  { id: "energetic", name: "Energetic", icon: "⚡", color: "from-green-400 to-emerald-400", translations: { en: "Energetic", hi: "ऊर्जावान", te: "శక్తివంతమైన" }},
   {
    id: "calm",
    name: "Calm",
    translations: {
      en: "Calm",
      es: "Tranquilo",
      fr: "Calme",
      de: "Ruhig",
      ja: "落ち着いた",
      te: "శాంతియుక్తమైన",
      hi: "शांత",
    },
    color: "from-green-400 to-teal-500",
    icon: "🧘",
  },
  
  {
    id: "romantic",
    name: "Romantic",
    translations: {
      en: "Romantic",
      es: "Romántico",
      fr: "Romantique",
      de: "Romantisch",
      ja: "ロマンティック",
      te: "రోమాంటిక్",
      hi: "रोमांटिक",
    },
    color: "from-pink-400 to-rose-500",
    icon: "💕",
  },
  {
    id: "focus",
    name: "Focus",
    translations: {
      en: "Focus",
      es: "Enfoque",
      fr: "Concentration",
      de: "Fokus",
      ja: "集中",
      te: "దృష్టి",
      hi: "ध्यान",
    },
    color: "from-purple-500 to-indigo-600",
    icon: "🎯",
  },
]

export const MOCK_SONGS = [
 // { id: "1", title: "Happy – Pharrell Williams", artist: "Pharrell Williams", mood: "happy", language: "en", link: "https://www.youtube.com/watch?v=ZbZSe6N_BXs" },
  //{ id: "2", title: "Someone Like You – Adele", artist: "Adele", mood: "sad", language: "en", link: "https://www.youtube.com/watch?v=hLQl3WQQoQ0" },
  // { id: "3", title: "Believer – Imagine Dragons", artist: "Imagine Dragons", mood: "energetic", language: "en", link: "https://www.youtube.com/watch?v=7wtfhZwyrcc" },
 // Happy Mood Songs
  {
    id: "1",
    title: "Sunshine Dreams",
    artist: "The Bright Side",
    mood: "happy",
    audioUrl: "/songs/dream-frequencies-334805.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.Wf7e2RIP90BBgn8lWT6JQgHaHa?pid=Api&P=0&h=220",
    duration: 240,
    language: "en",
  },
  {
    id: "2",
    title: "Golden Hour",
    artist: "The Bright Side",
    mood: "happy",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    imageUrl: "https://huebliss.com/wp-content/uploads/2021/09/Gloden-hour-portrait.jpg",
    duration: 250,
    language: "en",
  },
  {
    id: "3",
    title: "Dancing in the Sun",
    artist: "Joy Makers",
    mood: "happy",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.y7wq84OHCjWGVlbxDYK7pwHaEJ?pid=Api&P=0&h=220",
    duration: 235,
    language: "en",
  },
  {
    id: "4",
    title: "Smile Again",
    artist: "Happy Vibes",
    mood: "happy",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.3G1ftMa76lkeqeGaKwHdcgHaD4?pid=Api&P=0&h=220",
    duration: 245,
    language: "en",
  },
  {
    id: "5",
    title: "Cheerful Moments",
    artist: "Sunny Days",
    mood: "happy",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.9lIfKb4fVdDnqE8KAkyoeQHaE8?pid=Api&P=0&h=220",
    duration: 255,
    language: "en",
  },
  {
    id: "6",
    title: "Khushi Ka Geet",
    artist: "Bollywood Stars",
    mood: "happy",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.Wf7e2RIP90BBgn8lWT6JQgHaHa?pid=Api&P=0&h=220",
    duration: 260,
    language: "hi",
  },
  {
    id: "7",
    title: "Ananda Geetam",
    artist: "Telugu Classics",
    mood: "happy",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    imageUrl: "https://huebliss.com/wp-content/uploads/2021/09/Gloden-hour-portrait.jpg",
    duration: 250,
    language: "te",
  },

    // Sad Mood Songs
  {
    id: "8",
    title: "Midnight Thoughts",
    artist: "Luna Echo",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    imageUrl: "https://wallpapercave.com/wp/wp8300059.jpg",
    duration: 280,
    language: "en",
  },
  {
    id: "9",
    title: "Rainy Day Blues",
    artist: "Luna Echo",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.Wf7e2RIP90BBgn8lWT6JQgHaHa?pid=Api&P=0&h=220",
    duration: 270,
    language: "en",
  },
  {
    id: "10",
    title: "Broken Hearts",
    artist: "Melancholy Souls",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.yRoSK_FJL6Sg9KRy-VwngwHaEK?pid=Api&P=0&h=220",
    duration: 290,
    language: "en",
  },
  {
    id: "11",
    title: "Lonely Nights",
    artist: "Silent Echoes",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.XHNljZCtg3B6p6mBVj6rFwHaFU?pid=Api&P=0&h=220",
    duration: 275,
    language: "en",
  },
  {
    id: "12",
    title: "Tears of Yesterday",
    artist: "Emotional Waves",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.EKyd-TeTf9IF8aJyktvruQAAAA?pid=Api&P=0&h=220",
    duration: 285,
    language: "en",
  },
  {
    id: "13",
    title: "Dil Ki Baat",
    artist: "Sad Melodies",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.wf0C556sTA4EbMR45jv6cQHaEK?pid=Api&P=0&h=220",
    duration: 280,
    language: "hi",
  },
  {
    id: "14",
    title: "Manasu Neevey",
    artist: "Telugu Emotions",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    imageUrl: "https://huebliss.com/wp-content/uploads/2021/09/Gloden-hour-portrait.jpg",
    duration: 275,
    language: "te",
  },

  // Energetic Mood Songs
  {
    id: "15",
    title: "Electric Pulse",
    artist: "Neon Vibes",
    mood: "energetic",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.1mji0ItGXzvO5dowETMJcwAAAA?pid=Api&P=0&h=220",
    duration: 220,
    language: "en",
  },
  {
    id: "16",
    title: "Adrenaline Rush",
    artist: "Neon Vibes",
    mood: "energetic",
    audioUrl: "/songs/separated-forever-271975.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.rQu7Zm0JOccQB8Q1xiot_gHaHa?pid=Api&P=0&h=220",
    duration: 210,
    language: "en",
  },
  {
    id: "17",
    title: "Power Up",
    artist: "Energy Boosters",
    mood: "energetic",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-17.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.wf0C556sTA4EbMR45jv6cQHaEK?pid=Api&P=0&h=220",
    duration: 215,
    language: "en",
  },
  {
    id: "18",
    title: "Unstoppable",
    artist: "Force Majeure",
    mood: "energetic",
    audioUrl: "/songs/fun-and-inspirational-rap-beat-commercial-amp-free-download-129287.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.KK25uzHd4KdfGAxXd6fWMAHaI4?pid=Api&P=0&h=220",
    duration: 225,
    language: "en",
  },
  {
    id: "19",
    title: "Rocket Fuel",
    artist: "Speed Demons",
    mood: "energetic",
    audioUrl: "/songs/gungho-198707.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.YQQfsYrVEggRUDPdWly8ywHaFS?pid=Api&P=0&h=220",
    duration: 230,
    language: "en",
  },
  {
    id: "20",
    title: "Shakti Geet",
    artist: "Energy Masters",
    mood: "energetic",
    audioUrl: "/songs/fun-and-inspirational-rap-beat-commercial-amp-free-download-129287.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.b7wHegByv6wm5Ei67LAZaAHaE8?pid=Api&P=0&h=220",
    duration: 220,
    language: "hi",
  },
  {
    id: "21",
    title: "Vega Vega",
    artist: "Telugu Beats",
    mood: "energetic",
    audioUrl: "/songs/royalty-free-music-download-287173.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.zDeMj30fjhhprOZA5xz6QQHaGz?pid=Api&P=0&h=220",
    duration: 215,
    language: "te",
  },
   // Calm Mood Songs
  {
    id: "22",
    title: "Peaceful Waters",
    artist: "Zen Masters",
    mood: "calm",
    audioUrl: "/songs/fun-and-inspirational-rap-beat-commercial-amp-free-download-129287.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.8qneRBur6fxybwsuYZ-7agHaEK?pid=Api&P=0&h=220",
    duration: 300,
    language: "en",
  },
  {
    id: "23",
    title: "Serenity Now",
    artist: "Zen Masters",
    mood: "calm",
    audioUrl: "/songs/dream-frequencies-334805.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.Dscs4QKDf2DIceDTXrdSdAHaIc?pid=Api&P=0&h=220",
    duration: 310,
    language: "en",
  },
  {
    id: "24",
    title: "Meditation Flow",
    artist: "Calm Vibes",
    mood: "calm",
    audioUrl: "/songs/indian-hindi-song-diwali-background-music-294020.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.xZJ-F8XwMbrcDAn-ETxI5QHaEK?pid=Api&P=0&h=220",
    duration: 320,
    language: "en",
  },
  {
    id: "25",
    title: "Gentle Breeze",
    artist: "Nature Sounds",
    mood: "calm",
    audioUrl: "/songs/for-her-chill-upbeat-summel-travel-vlog-and-ig-music-royalty-free-use-202298.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.-qAtetKpY7t8tCfk4Y-hWgHaEK?pid=Api&P=0&h=220",
    duration: 305,
    language: "en",
  },
  {
    id: "26",
    title: "Tranquil Dreams",
    artist: "Sleep Sounds",
    mood: "calm",
    audioUrl: "/songs/fun-and-inspirational-rap-beat-commercial-amp-free-download-129287.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.4FWpyJiXlaQjqoG1wCIDfgHaEK?pid=Api&P=0&h=220",
    duration: 315,
    language: "en",
  },
  {
    id: "27",
    title: "Shanti Sangeet",
    artist: "Calm Masters",
    mood: "calm",
    audioUrl: "/songs/afro-trap-fusion-cna-beats-112526.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.RH9h1FNlD9mvIYYHCUm1iQHaHa?pid=Api&P=0&h=220",
    duration: 310,
    language: "hi",
  },
  {
    id: "28",
    title: "Shanthi Geetam",
    artist: "Telugu Calm",
    mood: "calm",
    audioUrl: "/songs/dream-frequencies-334805.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.NgK_ION1IMs1CFEjZd0lugHaEK?pid=Api&P=0&h=220",
    duration: 305,
    language: "te",
  },

  // Romantic Mood Songs
  {
    id: "29",
    title: "Love in the Air",
    artist: "Heart Strings",
    mood: "romantic",
    audioUrl: "/songs/romance.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.2Na9YAp8nj2zYWmuT_lpxAHaLH?pid=Api&P=0&h=220",
    duration: 260,
    language: "en",
  },
  {
    id: "30",
    title: "Moonlight Romance",
    artist: "Romantic Souls",
    mood: "romantic",
    audioUrl: "/songs/royalty-free-music-download-287173.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.PFEt50I-ghLl7aS4pLYBqwHaEK?pid=Api&P=0&h=220",
    duration: 270,
    language: "en",
  },
  {
    id: "31",
    title: "Forever With You",
    artist: "Love Ballads",
    mood: "romantic",
    audioUrl: "/songs/separated-forever-271975.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.KK25uzHd4KdfGAxXd6fWMAHaI4?pid=Api&P=0&h=220",
    duration: 265,
    language: "en",
  },
  {
    id: "32",
    title: "Starlight Serenade",
    artist: "Romantic Vibes",
    mood: "romantic",
    audioUrl: "/songs/gungho-198707.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.QL-kx15-Mu81jZfG3PtoxAHaHa?pid=Api&P=0&h=220",
    duration: 275,
    language: "en",
  },
  {
    id: "33",
    title: "Endless Love",
    artist: "Heart Melodies",
    mood: "romantic",
    audioUrl: "/songs/indian-hindi-song-diwali-background-music-294020.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.WqJd2nUc0501pU53l1gsRAHaFj?pid=Api&P=0&h=220",
    duration: 280,
    language: "en",
  },
  {
    id: "34",
    title: "Pyaar Ki Baat",
    artist: "Romantic Hindi",
    mood: "romantic",
    audioUrl: "/songs/or-her-chill-upbeat-summel-travel-vlog-and-ig-music-royalty-free-use-202298.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.aulfaOgnJBxOMpK_jxcxAQHaEK?pid=Api&P=0&h=220",
    duration: 270,
    language: "hi",
  },
  {
    id: "35",
    title: "Premalo Geetam",
    artist: "Telugu Romance",
    mood: "romantic",
    audioUrl: "/songs/fun-and-inspirational-rap-beat-commercial-amp-free-download-129287.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.JWKJI721xOe0k5hWLQx7pAHaHa?pid=Api&P=0&h=220",
    duration: 265,
    language: "te",
  },

  // Focus Mood Songs
  {
    id: "36",
    title: "Deep Focus",
    artist: "Study Beats",
    mood: "focus",
    audioUrl: "/songs/instrument-12092021-8362.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.rQu7Zm0JOccQB8Q1xiot_gHaHa?pid=Api&P=0&h=220",
    duration: 320,
    language: "en",
  },
  {
    id: "37",
    title: "Concentration Zone",
    artist: "Focus Masters",
    mood: "focus",
    audioUrl: "/songs/afro-trap-fusion-cna-beats-112526.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.dK3Ez-i6IpOY3TS3_wR9zgHaHa?pid=Api&P=0&h=220",
    duration: 330,
    language: "en",
  },
  {
    id: "38",
    title: "Productive Hours",
    artist: "Work Vibes",
    mood: "focus",
    audioUrl: "/songs/indian-hindi-song-diwali-background-music-294020.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.snAQSywXJLiveyZPVgidcwHaD2?pid=Api&P=0&h=220",
    duration: 325,
    language: "en",
  },
  {
    id: "39",
    title: "Mind Clear",
    artist: "Clarity Sounds",
    mood: "focus",
    audioUrl: "/songs/royalty-free-music-download-287173.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.wWbOCJBXN5KaIGCVSOJ--AHaE8?pid=Api&P=0&h=220",
    duration: 315,
    language: "en",
  },
  {
    id: "40",
    title: "Flow State",
    artist: "Focus Beats",
    mood: "focus",
    audioUrl: "/songs/romance.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.OtUWc-pROkVW20ifuxHVUgHaEK?pid=Api&P=0&h=220",
    duration: 335,
    language: "en",
  },
  {
    id: "41",
    title: "Dhyan Sangeet",
    artist: "Focus Hindi",
    mood: "focus",
    audioUrl: "/songs/fun-and-inspirational-rap-beat-commercial-amp-free-download-129287.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.necifA03Xh0shinwI-orUgHaHa?pid=Api&P=0&h=220",
    duration: 320,
    language: "hi",
  },
  {
    id: "42",
    title: "Dhyana Geetam",
    artist: "Telugu Focus",
    mood: "focus",
    audioUrl: "/songs/dream-frequencies-334805.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.WmDNnaT-lptuGT4LIWhnPwHaEK?pid=Api&P=0&h=220",
    duration: 325,
    language: "te",
  },

  // Additional variety songs
  {
    id: "43",
    title: "Vibrant Energy",
    artist: "Pulse Makers",
    mood: "energetic",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-43.mp3",
    imageUrl: "https://wallpapercave.com/wp/wp8300059.jpg",
    duration: 218,
    language: "en",
  },
  {
    id: "44",
    title: "Joyful Celebration",
    artist: "Happy Beats",
    mood: "happy",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-44.mp3",
    imageUrl: "https://wallpapercave.com/wp/wp8300059.jpg",
    duration: 248,
    language: "en",
  },
  {
    id: "45",
    title: "Whispered Secrets",
    artist: "Soft Melodies",
    mood: "romantic",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-45.mp3",
    imageUrl: "https://wallpapercave.com/wp/wp8300059.jpg",
    duration: 268,
    language: "en",
  },
  {
    id: "46",
    title: "Ocean Waves",
    artist: "Nature Therapy",
    mood: "calm",
    audioUrl: "/songs/instrument-12092021-8362.mp3",
    imageUrl: "https://wallpapercave.com/wp/wp8300059.jpg",
    duration: 318,
    language: "en",
  },
  {
    id: "47",
    title: "Silent Reflection",
    artist: "Quiet Moments",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-47.mp3",
    imageUrl: "https://wallpapercave.com/wp/wp8300059.jpg",
    duration: 288,
    language: "en",
  },
  {
    id: "48",
    title: "Raat Ki Khushboo",
    artist: "Hindi Classics",
    mood: "romantic",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-48.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.QfehCiAFYYpQjUgOaxVoaQHaEK?pid=Api&P=0&h=220",
    duration: 272,
    language: "hi",
  },
  {
    id: "49",
    title: "Chandamama",
    artist: "Telugu Classics",
    mood: "calm",
    audioUrl: "/songs/afro-trap-fusion-cna-beats-112526.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.cAKHZ4hC6fzqgihzoiKowAHaEK?pid=Api&P=0&h=220",
    duration: 312,
    language: "te",
  },
  {
    id: "50",
    title: "Bhangra Beats",
    artist: "Hindi Energy",
    mood: "energetic",
    audioUrl: "/songs/indian-hindi-song-diwali-background-music-294020.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP._ZcaDquzMbHHgbuZzUQwAAHaHf?pid=Api&P=0&h=220",
    duration: 225,
    language: "hi",
  },

  // Happy Mood - Additional Songs
  {
    id: "51",
    title: "Bright Horizon",
    artist: "Sunny Vibes",
    mood: "happy",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    imageUrl: "https://i.pinimg.com/originals/8b/dd/24/8bdd24e35e3a2adc9a439d9b60a4a69c.jpg",
    duration: 242,
    language: "en",
  },
  {
    id: "52",
    title: "Rainbow Days",
    artist: "Color Splash",
    mood: "happy",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.1oOFj7hEOT8-2wxHMqZcKAHaHa?pid=Api&P=0&h=220",
    duration: 238,
    language: "en",
  },
  {
    id: "53",
    title: "Khushiyon Ka Rang",
    artist: "Bollywood Joy",
    mood: "happy",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.7EfkzkqnlJXqQq6bXYVGggHaFj?pid=Api&P=0&h=220",
    duration: 255,
    language: "hi",
  },
  {
    id: "54",
    title: "Santhosham Geetam",
    artist: "Telugu Joy",
    mood: "happy",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.wMurmN6obNoc3Maidn96-wHaJ4?pid=Api&P=0&h=220",
    duration: 250,
    language: "te",
  },
  {
    id: "55",
    title: "Laughter Echo",
    artist: "Fun Times",
    mood: "happy",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.VaBaWKaCGZ7mtP3RUi6hOwHaEK?pid=Api&P=0&h=220",
    duration: 245,
    language: "en",
  },

  // Sad Mood - Additional Songs
  {
    id: "56",
    title: "Echoes of Loss",
    artist: "Melancholy",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.xD01Ih-GJla235CVODW6AQHaEK?pid=Api&P=0&h=220",
    duration: 285,
    language: "en",
  },
  {
    id: "57",
    title: "Forgotten Dreams",
    artist: "Silent Sorrow",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.426jIYFWYzj4tSsKGST46wHaKb?pid=Api&P=0&h=220",
    duration: 295,
    language: "en",
  },
  {
    id: "58",
    title: "Dukh Ki Kahani",
    artist: "Hindi Sadness",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    imageUrl: "https://up.yimg.com/ib/th/id/OIP.XDRzeJGHpSdE5t6W1kI5AQHaEK?pid=Api&rs=1&c=1&qlt=95&w=203&h=114",
    duration: 290,
    language: "hi",
  },
  {
    id: "59",
    title: "Vishada Geetam",
    artist: "Telugu Sorrow",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.XDRzeJGHpSdE5t6W1kI5AQHaEK?pid=Api&P=0&h=220",
    duration: 280,
    language: "te",
  },
  {
    id: "60",
    title: "Fading Away",
    artist: "Quiet Tears",
    mood: "sad",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.rmOelB7hKafhIFIFSMrhPAHaHa?pid=Api&P=0&h=220",
    duration: 275,
    language: "en",
  },

  // Energetic Mood - Additional Songs
  {
    id: "61",
    title: "Lightning Strike",
    artist: "Thunder Beats",
    mood: "energetic",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.xZJ-F8XwMbrcDAn-ETxI5QHaEK?pid=Api&P=0&h=220",
    duration: 220,
    language: "en",
  },
  {
    id: "62",
    title: "Turbo Charged",
    artist: "Speed Kings",
    mood: "energetic",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.bgablokg5a1EEQzwf5Q8sgHaLH?pid=Api&P=0&h=220",
    duration: 215,
    language: "en",
  },
  {
    id: "63",
    title: "Tej Gati",
    artist: "Hindi Energy",
    mood: "energetic",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.dJoXabWPWI3jep-614z0uwHaHa?pid=Api&P=0&h=220",
    duration: 225,
    language: "hi",
  },
  {
    id: "64",
    title: "Vega Vega Geetam",
    artist: "Telugu Energy",
    mood: "energetic",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.fd4qhySeh4WvBjTknogOYgHaEK?pid=Api&P=0&h=220",
    duration: 220,
    language: "te",
  },
  {
    id: "65",
    title: "Explosive Energy",
    artist: "Boom Beats",
    mood: "energetic",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.TdZdRPsv_4LRGjGjqiRskwHaEK?pid=Api&P=0&h=220",
    duration: 228,
    language: "en",
  },

  // Calm Mood - Additional Songs
  {
    id: "66",
    title: "Soft Whispers",
    artist: "Calm Essence",
    mood: "calm",
    audioUrl: "/songs/instrument-12092021-8362.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.es09Ccpt-Ba-8HBkzU4dvwHaHa?pid=Api&P=0&h=220",
    duration: 310,
    language: "en",
  },
  {
    id: "67",
    title: "Twilight Peace",
    artist: "Evening Calm",
    mood: "calm",
    audioUrl: "/songs/royalty-free-music-download-287173.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.xZJ-F8XwMbrcDAn-ETxI5QHaEK?pid=Api&P=0&h=220",
    duration: 315,
    language: "en",
  },
  {
    id: "68",
    title: "Shanti Sangeet",
    artist: "Hindi Calm",
    mood: "calm",
    audioUrl: "/songs/instrument-12092021-8362.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.nr5Ryn4d7XqhO0w3aGgcrAHaHa?pid=Api&P=0&h=220",
    duration: 312,
    language: "hi",
  },
  {
    id: "69",
    title: "Shanthi Geetam",
    artist: "Telugu Calm",
    mood: "calm",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.NgK_ION1IMs1CFEjZd0lugHaEK?pid=Api&P=0&h=220",
    duration: 308,
    language: "te",
  },
  {
    id: "70",
    title: "Harmony Flow",
    artist: "Balance Vibes",
    mood: "calm",
    audioUrl: "/songs/dream-frequencies-334805.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.X_QCXGiR77tGyLTMFCGrFQHaHa?pid=Api&P=0&h=220",
    duration: 320,
    language: "en",
  },

  // Romantic Mood - Additional Songs
  {
    id: "71",
    title: "Tender Hearts",
    artist: "Love Echoes",
    mood: "romantic",
    audioUrl: "/songs/afro-trap-fusion-cna-beats-112526.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.Vm5P5Era6oNXmvPEjW8n8QHaEK?pid=Api&P=0&h=220",
    duration: 268,
    language: "en",
  },
  {
    id: "72",
    title: "Sunset Romance",
    artist: "Golden Love",
    mood: "romantic",
    audioUrl: "/songs/romance.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.nOVyJ_TAoia7yBnjDrD93wHaE8?pid=Api&P=0&h=220",
    duration: 272,
    language: "en",
  },
  {
    id: "73",
    title: "Pyaar Ke Pal",
    artist: "Hindi Romance",
    mood: "romantic",
    audioUrl: "/songs/for-her-chill-upbeat-summel-travel-vlog-and-ig-music-royalty-free-use-202298.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.AmvG1I5rul2UN1qFnuLpmwHaEK?pid=Api&P=0&h=220",
    duration: 270,
    language: "hi",
  },
  {
    id: "74",
    title: "Premanam Geetam",
    artist: "Telugu Romance",
    mood: "romantic",
    audioUrl: "/songs/instrument-12092021-8362.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.yY_JznMCy3PW5bLK9SwcdwHaEK?pid=Api&P=0&h=220",
    duration: 268,
    language: "te",
  },
  {
    id: "75",
    title: "Eternal Devotion",
    artist: "Forever Love",
    mood: "romantic",
    audioUrl: "/songs/afro-trap-fusion-cna-beats-112526.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.3TmzdZuZNiJPdF0Nj6jbFwHaEK?pid=Api&P=0&h=220",
    duration: 275,
    language: "en",
  },

  // Focus Mood - Additional Songs
  {
    id: "76",
    title: "Zen Workspace",
    artist: "Focus Flow",
    mood: "focus",
    audioUrl: "/songs/dream-frequencies-334805.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.d8mB3IhNM7B4Ndvyla4AEwHaEK?pid=Api&P=0&h=220",
    duration: 328,
    language: "en",
  },
  {
    id: "77",
    title: "Brain Power",
    artist: "Study Vibes",
    mood: "focus",
    audioUrl: "/songs/indian-hindi-song-diwali-background-music-294020.mp3",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.Zeqza_aXo30qPYrVp8n59gHaHa?pid=Api&P=0&h=220",
    duration: 332,
    language: "en",
  },
  {
    id: "78",
    title: "Dhyan Sangeet",
    artist: "Hindi Focus",
    mood: "focus",
    audioUrl: "/songs/instrument-12092021-8362.mp3",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.8keZF7dqVYP68X77Gc4K6QHaDt?pid=Api&P=0&h=220",
    duration: 325,
    language: "hi",
  },
  {
    id: "79",
    title: "Dhyana Geetam",
    artist: "Telugu Focus",
    mood: "focus",
    audioUrl: "/songs/separated-forever-271975.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.xZJ-F8XwMbrcDAn-ETxI5QHaEK?pid=Api&P=0&h=220",
    duration: 330,
    language: "te",
  },
  {
    id: "80",
    title: "Clarity Mind",
    artist: "Mental Focus",
    mood: "focus",
    audioUrl: "/songs/afro-trap-fusion-cna-beats-112526.mp3",
    imageUrl: "https://tse2.mm.bing.net/th/id/OIP.1mji0ItGXzvO5dowETMJcwAAAA?pid=Api&P=0&h=220",
    duration: 338,
    language: "en",
  },


]

export const PROFESSIONS = [ "Software Engineer",
  "Designer",
  "Student",
  "Teacher",
  "Doctor",
  "Artist",
  "Musician",
  "Writer",
  "Entrepreneur",
  "Manager",
  "Other",
];
export const INTERESTS = ["Technology",
  "Art",
  "Music",
  "Sports",
  "Travel",
  "Food",
  "Gaming",
  "Reading",
  "Fitness",
  "Nature",
];
